services:
  admin:
    build: .
    image: tarzon_store_admin
    ports:
      - "3001:3000"
    env_file:
      - ./.env.local
    volumes:
      - logs:/app/logs
    restart: unless-stopped

volumes:
  logs:
